#! /usr/bin/python

print "THIS IS AN OLD THING DON'T USE IT YOU WERE PROBABLY LOOKING FOR https://github.com/technoboy10/buzzfeed OR https://github.com/zippynk/buzzfeed/tree/patch-1"

import random
import string

def reasons():
    s = ' reasons why'
    s += ' ' + random.choice(['dogs', 'people', random.choice(['my ', '']) + 'shoes', random.choice(['other ', '']) +'tumblr users', 'smart people', 'disney movies', 'super bowl snacks', 'gifts', 'demonstrators', 'books', 'valentines', 'touchdowns', 'puppies', 'actors', 'actresses', 'cars', 'horoscopes']) + ' '
    s += 'are ' + random.choice(['annoying', 'horrible', 'awesome', 'insane', 'superlative', 'funny', 'wrong', 'right'])
    return s
def humanity():
    num = random.randint(3,60)
    s = 'These ' +str(num) +' '  +random.choice(['dogs', 'people', random.choice(['of my ', '']) + 'shoes', random.choice(['other ', '']) +'tumblr users', 'smart people', 'disney movies', 'super bowl snacks', 'gifts', 'demonstrators', 'books', 'valentines', 'touchdowns', 'puppies', 'actors', 'actresses', 'cars', 'horoscopes']) + ' will restore your faith in humanity' + random.choice(['', ' (You Won\'t Believe Number ' + str(random.randint(1, num)) + '!)'])
    return s
def cry():
    num = random.randint(3,60)
    s = 'These ' +str(num) +' '  +random.choice(['dogs', 'people', random.choice(['of my ', '']) + 'shoes', random.choice(['other ', '']) +'tumblr users', 'smart people', 'disney movies', 'super bowl snacks', 'gifts', 'demonstrators', 'books', 'valentines', 'touchdowns', 'puppies', 'actors', 'actresses', 'cars', 'horoscopes']) + ' will make you cry' + random.choice(['', ' (You Won\'t Believe Number ' + str(random.randint(1, num)) + '!)'])
    return s
def mostAbout():
    num = random.randint(3,60)
    s = 'The ' +str(num) +random.choice([random.choice([' best',' worst']), random.choice([' most annoying', ' most horrible', ' most awesome', ' most insane', ' funniest', ' wrongest', ' rightest'])]) + ' things about ' + random.choice(['dogs', 'people', random.choice(['my ', '']) + 'shoes', random.choice(['other ', '']) +'tumblr users', 'smart people', 'disney movies', 'super bowl snacks', 'gifts', 'demonstrators', 'books', 'valentines', 'touchdowns', 'puppies', 'actors', 'actresses', 'cars', 'horoscopes']) + random.choice(['', ' (You Won\'t Believe Number ' + str(random.randint(1, num)) + '!)'])
    return s

thing = random.randint(2,5)
if thing == 5:
    final = humanity()
elif thing == 4:
    final = cry()
elif thing == 3:
    final = mostAbout()
else:
    num = random.randint(2,60)
    final = ''
    final = str(num) + reasons() + random.choice(['.', '!', '', ])
    final = string.capwords(final) + random.choice(['', ' (You Won\'t Believe Number ' + str(random.randint(1, num)) + '!)'])
print final
